helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:8981ec4abc84fb94d87d44ab6a347ca6e6de2ac5ee2af814aeb5218913f42d66
    forcestring: true
