helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:b9f8fe2a96348bb0f52886781417d9056aaba4628f2718ce7c8af3489d0421fd
    forcestring: true
