helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:4bf7a22162fe8beec5bc73f0edde20d358f29c4e58af6ca340279e20dee1485b
    forcestring: true
