helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:4ce11330324fcd707dde44b515611fa58faf789384dac7ff562fe6e03169827e
    forcestring: true
