helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:bc332087cc44a95109eb138611bcc6f76b1008aafeffb498a245a25fc76cd0fd
    forcestring: true
