helm:
  parameters:
  - name: image.repository
    value: ghcr.io/mvs5465-test/loki-mcp-server
    forcestring: true
  - name: image.tag
    value: main@sha256:9e59f9780a0a0f2c19063f6e4068a6e645a4b792ec915846474bc6684ac45eaa
    forcestring: true
